version: "3.9"
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
